### ISSUE TITLE
removing booktitle field breaks processing for incollection items

### ISSUE THREAD

**Issue by chreliot** [twsh/Convertbibliography#2]
I double-checked the BibLaTeX manual, and the required fields for `incollection` entries are “`author, title, booktitle, year/date`.” The script is removing `booktitle` for these (as it states it does!), and it shouldn't. Biblatex obviously then necessarily leaves out book titles like: 

Author. "Chapter Title," edited by Editor. Address: Publisher. 

when correct output should be:

Author. "Chapter Title," in Book Title, edited by Editor. Address: Publisher. 

Thanks!

**Comment by twsh** [comment]
I did that because when I have an `incollection` I will have a `crossref` field and `booktitle` will inherit from its `title`. As you say, the script messes things up if you're not doing it that way.
